spring:
  application:
    name: ssutime
  datasource:
    url: ${DB_URL}

    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  cors:
    allowed-origins:
      - http://localhost:3000
      - https://ssu-time.vercel.app

cloud:
  aws:
    s3:
      bucket: "ssu-time-crawler-output"
    region:
      static: "ap-northeast-2"
mixpanel:
  token: ${MIXPANEL_TOKEN}
  event-name: ${MIXPANEL_EVENT_NAME}